version: '3'

services:
  migrate:
    image: 'ghcr.io/flexwie/monitoring_bot/migration:latest'
    env_file:
      - .env
    depends_on:
      - db
  bot:
    entrypoint: node dist/apps/monitoring_bot/main.js
    image: 'ghcr.io/flexwie/monitoring_bot/bot:latest'
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - migrate
  billing:
    entrypoint: node dist/apps/billing/main.js
    image: 'ghcr.io/flexwie/monitoring_bot/billing:latest'
    env_file:
      - .env
    ports:
      - 3001:3001
    depends_on:
      - migrate
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: CHANGEME
      POSTGRES_USER: mbot
      POSTGRES_DB: mbot

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass CHANGEME
    volumes:
      - redis_data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  redis_data: