version: '3'

services:
  bot:
    entrypoint: node dist/apps/monitoring_bot/main.js
    build:
      context: .
      dockerfile: Dockerfile
      args:
        target: monitoring_bot
    env_file:
      - .env
    ports:
      - 3000:3000
  billing:
    entrypoint: node dist/apps/billing/main.js
    build:
      context: .
      dockerfile: Dockerfile
      args:
        target: billing
    env_file:
      - .env
    ports:
      - 3001:3001
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: oeirgneoran
      POSTGRES_USER: mbot
      POSTGRES_DB: mbot
    ports:
      - 5432:5432

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass eogrno
    ports:
      - 6379:6379
    volumes:
      - redis_data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  redis_data: