apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
apiVersion: v1
kind: Pod
metadata:
  name: bot
  namespace: apps
spec:
  initContainers:
  - name: migrate
    image: ghcr.io/flexwie/monitoring_bot/migration:latest
    env:
      - name: DATABASE_URL
        value: file:/db/dev.db
    volumeMounts:
    - mountPath: /db
      name: db
  containers:
  - name: bot
    image: ghcr.io/flexwie/monitoring_bot/bot:latest
    args: ["node", "dist/apps/monitoring_bot/main.js"]
    envFrom:
      - secretRef:
          name: appenv
    volumeMounts:
    - mountPath: /db
      name: db
  volumes:
    - name: db
      persistentVolumeClaim:
        claimName: bot
---
apiVersion: v1
kind: Secret
metadata:
  name: appenv
  namespace: apps
type: Opaque
stringData:
  BOT_TOKEN: 5560006353:AAHW31VTZh0RaF__N90DJYExlwMX19ukW9U
  AAD_TENANT_ID: 9d37ea75-9d75-4de4-b02a-cd91a6b02eb4
  AAD_CLIENT_ID: 23c1bbc2-22c1-4dc5-88ca-3bc8bb2f68fc
  REDIS_HOST: localhost
  REDIS_PASSWORD: test
  DB_SECRET: aoeignoerün
  DATABASE_URL: file:/db/dev.db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bot
  namespace: apps
spec:
  resources:
    requests: 
      storage: 1Gi
  storageClassName: azureblob-fuse-premium
  accessModes:
    - ReadWriteMany

